// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIzxrBGbYGB845PdKtRkQRfs5tK_uP4bc',
    appId: '1:926420600711:web:bea2b668777a63b046b522',
    messagingSenderId: '926420600711',
    projectId: 'ig-clone-c2f3b',
    authDomain: 'ig-clone-c2f3b.firebaseapp.com',
    storageBucket: 'ig-clone-c2f3b.appspot.com',
    measurementId: 'G-MNPS97YVL5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAxw3jfij9p5dny-SSYHgOjiZ6a0jTOa4',
    appId: '1:926420600711:android:0608e1db56e581bf46b522',
    messagingSenderId: '926420600711',
    projectId: 'ig-clone-c2f3b',
    storageBucket: 'ig-clone-c2f3b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_Q1g0hO4ksTYdSuGKj-OhK1q3Ux81K2I',
    appId: '1:926420600711:ios:3bcdfe093771e3d346b522',
    messagingSenderId: '926420600711',
    projectId: 'ig-clone-c2f3b',
    storageBucket: 'ig-clone-c2f3b.appspot.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_Q1g0hO4ksTYdSuGKj-OhK1q3Ux81K2I',
    appId: '1:926420600711:ios:f846eab0de92310b46b522',
    messagingSenderId: '926420600711',
    projectId: 'ig-clone-c2f3b',
    storageBucket: 'ig-clone-c2f3b.appspot.com',
    iosBundleId: 'com.example.instagramClone.RunnerTests',
  );
}
